# Generated by Django 5.0.1 on 2024-09-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='Example-slug', unique=True),
            preserve_default=False,
        ),
    ]
